import { registerPreparedAccountingEffectCases } from "./prepared-purchase-accounting-effects.cases.js";
import { registerPreparedCapabilityEffectCases } from "./prepared-purchase-capability-effects.cases.js";
import { registerPreparedContextEffectCases } from "./prepared-purchase-context-effects.cases.js";
import { registerPreparedEventLogEffectCases } from "./prepared-purchase-event-log-effects.cases.js";
import { registerPreparedFactoryEffectCases } from "./prepared-purchase-factory-effects.cases.js";
import { registerPreparedFactoryResultCases } from "./prepared-purchase-factory-result.cases.js";
import { registerPreparedFetchEffectCases } from "./prepared-purchase-fetch-effects.cases.js";
import { registerPreparedHoldingEffectCases } from "./prepared-purchase-holding-effects.cases.js";
import { registerPreparedHoldingAuthorityCases } from "./prepared-purchase-holding-authority.cases.js";
import { registerPreparedHoldingStructureCases } from "./prepared-purchase-holding-structure.cases.js";
import { registerPreparedPreapprovalEffectCases } from "./prepared-purchase-preapproval-effects.cases.js";
import { registerPreparedPreapprovalResultCases } from "./prepared-purchase-preapproval-result.cases.js";
import { registerPreparedSottoStructureCases } from "./prepared-purchase-sotto-structure.cases.js";
import { registerPreparedUpgradeEffectCases } from "./prepared-purchase-upgrade-effects.cases.js";

registerPreparedFactoryEffectCases();
registerPreparedFactoryResultCases();
registerPreparedCapabilityEffectCases();
registerPreparedContextEffectCases();
registerPreparedSottoStructureCases();
registerPreparedHoldingEffectCases();
registerPreparedHoldingAuthorityCases();
registerPreparedAccountingEffectCases();
registerPreparedHoldingStructureCases();
registerPreparedFetchEffectCases();
registerPreparedPreapprovalEffectCases();
registerPreparedPreapprovalResultCases();
registerPreparedEventLogEffectCases();
registerPreparedUpgradeEffectCases();
